### PR TITLE
When performing validation use a subset of training data

### PR DESCRIPTION
**Pull request by Pattio**
Hey, currently DEvol uses testing data as validation data, which means that the final model will be biased. Wouldn't it be better to just split 10% of training data and use that as a validation data?

### CODE REVIEW

**Comment by joeddav** [comment]
That would make sense. The assumption right now is that the validation data you pass is indeed validation data, but the way the demos are constructed doesn't reflect that. Should be a very simple change.

**Comment by Pattio** [comment]
But there doesn't seem to be a way to pass validation data at the moment, as the only data it expects is train and test:

`(self.x_train, self.y_train), (self.x_test, self.y_test) = dataset`

In new commit I added working version which uses validation data if it is given and otherwise it uses subset of training data.

**Comment by joeddav** [comment]
So it's called `x_test` and `y_test` in the code, but this is a misnomer since it's really only used for validation purposes. As the code is set up right now, there's no reason to even preserve `x_test` and `y_test`, since test data is never used in the proper sense. The expectation would be for the user to evaluate this on their own after optimizing.

So let's just rename `x_test` and `y_test` to `x_val` and `y_val`. I think it would make the most sense to actually change the API to pass `train_data` and `val_data` separately. If `val_data` is None (which would be the default), create a random split as you've done here.

**Comment by Pattio** [comment]
Indeed the naming is confusing. However, I still feel that using the same data for validation and evaluation is not good as it will impact the bias of the final model. I fully understand that the intention is to pass validation data, but the problem is that you are using it to early stop during the training and then later you are reusing it to evaluate the model's performance. Anyways if that's done intentionally I will close the PR 👍

**Comment by joeddav** [comment]
Sorry for the delayed response.

Yes, I see what you're saying. It's used to validate in two different places: 1) in early stopping of training a model, and 2) in evaluating one candidate's performance, which makes those evaluations biased. I misunderstood previously.

**Pull request merged**
